# Generated by Django 5.1.5 on 2025-01-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_remove_course_schedule_remove_course_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='name',
        ),
    ]
