# Generated by Django 5.1.5 on 2025-01-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
