# Generated by Django 5.1.5 on 2025-01-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_useradmin_accepted_useradmin_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='notified',
        ),
    ]
