# Generated by Django 5.1.5 on 2025-01-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_remove_useradmin_accepted_remove_useradmin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
