# Generated by Django 5.1.5 on 2025-02-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_alter_group_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='title',
        ),
    ]
