# Generated by Django 5.1.5 on 2025-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_rename_name_group_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='group',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='telegram_group_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
