# Generated by Django 5.1.5 on 2025-02-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_remove_course_title_remove_group_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
